name: otobo-ai


services:
  otobo-ai:
    build: .
    env_file:
      - .env

    ports:
      - 8080:8080
    restart: on-failure:5

  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - chromadb-data:/chroma
    restart: unless-stopped

volumes:
  chromadb-data:
