name: otobo-ai


services:
  otobo-ai:
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    restart: on-failure:5
    depends_on:
      - postgres
    environment:
      LANGFUSE_PUBLIC_KEY: ${OTOBO_AI_LANGFUSE_PK}
      LANGFUSE_SECRET_KEY: ${OTOBO_AI_LANGFUSE_SK}
      LANGFUSE_HOST: ${OTOBO_AI_LANGFUSE_HOST}
    volumes:
      - chromadb-data:/chroma
    command: >
      uvicorn src.server:app
      --host 0.0.0.0
      --port 8080
      --loop asyncio

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${OTOBO_AI_PG_DB}
      POSTGRES_USER: ${OTOBO_AI_PG_USER}
      POSTGRES_PASSWORD: ${OTOBO_AI_PG_PW}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-sql:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  chromadb-data:

  postgres-data:
