# Docker compose file for "Roboto", the OTOBO AI service.
# See also https://github.com/RotherOSS/otobo-ai-services#

# Use this override to expose the port out of the docker network

services:
  otobo-ai:
    build: ..
    # Expose the port to localhost
    ports:
      - "127.0.0.1:${OTOBO_AI_PORT:-8000}:${OTOBO_AI_PORT:-8000}"
