# Docker compose file for "Roboto", the OTOBO AI service.

# See also https://github.com/RotherOSS/otobo-ai-services#
# See also dockerhub...

services:
  otobo-ai:
    image: ${OTOBO_IMAGE_OTOBO_AI:-rotheross/otobo-ai-services:latest}
    restart: always
    depends_on:
      - postgres
    env_file:
      - ../.env
    environment:
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY}
      LANGFUSE_HOST: ${LANGFUSE_BASE_URL}
    volumes:
      - chromadb_data:/chroma
      - ../rags:/code/src/rags
    command: >
      uvicorn src.server:app
      --host ${OTOBO_AI_HOST}
      --port ${OTOBO_AI_PORT}
      --loop asyncio

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${OTOBO_AI_PG_DB}
      POSTGRES_USER: ${OTOBO_AI_PG_USER}
      POSTGRES_PASSWORD: ${OTOBO_AI_PG_PW}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../src/init-sql:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  chromadb_data: {}
  postgres_data: {}
