# Docker compose file for "Roboto", the OTOBO AI service.

# See also https://github.com/RotherOSS/otobo-ai-services#

services:
  otobo-ai:
    # build from local Dockerfile
    build: ..
    image: !reset null
