# Docker compose file for "Roboto", the OTOBO AI service.

# See also https://github.com/RotherOSS/otobo-ai-services#
# See also dockerhub...

services:
  rag:
    image: ${OTOBO_IMAGE_OTOBO_AI:-rotheross/otobo-ai-services:latest}
    restart: always
    env_file:
      - ../.env
    environment:
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY}
      LANGFUSE_HOST: ${LANGFUSE_BASE_URL}
    volumes:
      - chromadb_data:/chroma
      - ../rags:/code/src/rags
    command: >
      uvicorn src.server:app
      --host ${OTOBO_AI_HOST}
      --port ${OTOBO_AI_PORT}
      --loop asyncio

volumes:
  chromadb_data: {}
