services:
  chat:
    image: ghcr.io/open-webui/open-webui:0.10-slim
    ports:
      - "3000:8080"
    env_file:
      ../.env
    environment:
      - OPENAI_API_MODELS=${OPENAI_API_MODELS:-${OTOBO_AI_LLM_MODEL}}
      - DEFAULT_MODELS=${DEFAULT_MODELS:-${OTOBO_AI_LLM_MODEL}}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-${OTOBO_AI_LLM_API_KEY}}
      - OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL:-${OTOBO_AI_LLM_HOST}/v1}
      - ENABLE_OPENAI_API=${ENABLE_OPENAI_API:-True}
      - ENABLE_SIGNUP=${ENABLE_SIGNUP:-False}
      - DEFAULT_LOCALE=${DEFAULT_LOCALE:-en}
      - ENABLE_PERSISTENT_CONFIG=${ENABLE_PERSISTENT_CONFIG:-True}
      - ENABLE_CALENDAR=${ENABLE_CALENDAR:-False}
      - ENABLE_FOLDERS=${ENABLE_FOLDERS:-False}
      - ENABLE_MEMORIES=${ENABLE_MEMORIES:-True}
      - ENABLE_NOTES=${ENABLE_NOTES:-False}
      - ENABLE_MEMORY_SYSTEM_CONTEXT=${ENABLE_MEMORY_SYSTEM_CONTEXT:-False}
      - ENABLE_CODE_EXECUTION=${ENABLE_CODE_EXECUTION:-False}
      - ENABLE_MESSAGE_RATING=${ENABLE_MESSAGE_RATING:-False}
      - ENABLE_COMMUNITY_SHARING=${ENABLE_COMMUNITY_SHARING:-False}
      - ENABLE_AUTOMATIONS=${ENABLE_AUTOMATIONS:-False}
      - TOOL_SERVER_CONNECTIONS=${TOOL_SERVER_CONNECTIONS}
    volumes:
      - chat:/app/backend/data
    networks:
      - otobo_default

volumes:
  chat:
