services:
  chat:
    image: ghcr.io/open-webui/open-webui:${OPENWEBUI_IMAGE_VERSION:-0.11.2-slim}
      #    ports:
      #      - "3000:8080"
    deploy:
      resources:
        limits:
          memory: 4G      # Adjust based on usage
          cpus: '2.0'
    restart: unless-stopped
    env_file:
      ../.env
    environment:
      - AUDIO_STT_ENGINE=${AUDIO_SST_ENGINE:-webapi}
      - DATABASE_POOL_SIZE=${DATABASE_POOL_SIZE:-16}
      - DATABASE_SQLITE_PRAGMA_CACHE_SIZE=${DATABASE_SQLITE_PRAGMA_CACHE_SIZE:--2000}
      - DATABASE_SQLITE_PRAGMA_MMAP_SIZE=${DATABASE_SQLITE_PRAGMA_MMAP_SIZE:-0}
      - DEFAULT_LOCALE=${DEFAULT_LOCALE:-en}
      - DEFAULT_MODELS=${DEFAULT_MODELS:-${OTOBO_AI_LLM_MODEL}}
      - ENABLE_AUTOCOMPLETE_GENERATION=${ENABLE_AUTOCOMPLETE_GENERATION:-False}
      - ENABLE_AUTOMATIONS=${ENABLE_AUTOMATIONS:-False}
      - ENABLE_BASE_MODELS_CACHE=${ENABLE_BASE_MODELS_CACHE:-True}
      - ENABLE_CALENDAR=${ENABLE_CALENDAR:-False}
      - ENABLE_CODE_EXECUTION=${ENABLE_CODE_EXECUTION:-False}
      - ENABLE_CODE_INTERPRETER=${ENABLE_CODE_INTERPRETER:-False}
      - ENABLE_COMMUNITY_SHARING=${ENABLE_COMMUNITY_SHARING:-False}
      - ENABLE_FOLDERS=${ENABLE_FOLDERS:-False}
      - ENABLE_MEMORIES=${ENABLE_MEMORIES:-True}
      - ENABLE_MEMORY_SYSTEM_CONTEXT=${ENABLE_MEMORY_SYSTEM_CONTEXT:-False}
      - ENABLE_MESSAGE_RATING=${ENABLE_MESSAGE_RATING:-False}
      - ENABLE_NOTES=${ENABLE_NOTES:-False}
      - ENABLE_OPENAI_API=${ENABLE_OPENAI_API:-True}
      - ENABLE_PERSISTENT_CONFIG=${ENABLE_PERSISTENT_CONFIG:-True}
      - ENABLE_SIGNUP=${ENABLE_SIGNUP:-False}
      - ENABLE_TAGS_GENERATION=${ENABLE_TAGS_GENERATION:-False}
      - MODELS_CACHE_TTL=${MODELS_CACHE_TTL:-600}
      - OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL:-${OTOBO_AI_LLM_HOST}/v1}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-${OTOBO_AI_LLM_API_KEY}}
      - OPENAI_API_MODELS=${OPENAI_API_MODELS:-${OTOBO_AI_LLM_MODEL}}
      - TOOL_SERVER_CONNECTIONS=${TOOL_SERVER_CONNECTIONS}
    volumes:
      - chat:/app/backend/data
    networks:
      - otobo_default

volumes:
  chat:
